# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60b5e890a33dd27baca0f9e52a4c02a332f98d148f85fe47405f08f750ecac455f46fcbbe5dbfa6dff5462293c9997f3d64c6031c107abf9a9f9fc0f0d8f94fd

test:
  secret_key_base: c4d2aa5f9d41e0b06c38f9eb8e9cc583d552760d30d2e318da0ac77422b8aed2fd34f9ca3ead521ef40b68ea3e1bfcb9440b0b487f403994a69505f034212a9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
